import Vue from 'vue'
import Vuex from 'vuex'

import actions from './actions'
import mutations from './mutations'

Vue.use(Vuex)

const store = new Vuex.Store({
  state:{
    anxiousQuestion:[//7项广泛性焦虑障碍量表（GAD-7）
        {
            id:'1001',
            type:'1',
            order:1,//问题显示顺序
            question:'感觉紧张、焦虑或烦躁？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                    'select':false
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1005',
            type:'1',//问题类型1单选，2多选
            order:5,//问题显示顺序
            question:'不能停止或控制担忧？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1010',
            type:'1',//问题类型1单选，2多选
            order:10,//问题显示顺序
            question:'对各种各样的事情担忧过多？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1015',
            type:'1',//问题类型1单选，2多选
            order:15,//问题显示顺序
            question:'很难放松下来？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1020',
            type:'1',//问题类型1单选，2多选
            order:20,//问题显示顺序
            question:'由于不安而无法安静坐？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1025',
            type:'1',//问题类型1单选，2多选
            order:25,//问题显示顺序
            question:'变得容易烦躁或急躁？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1030',
            type:'1',//问题类型1单选，2多选
            order:30,//问题显示顺序
            question:'害怕将有可怕的事发生？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
    ],
    healthyQuestion:[//9项患者健康问卷（PHQ-9）
        {
            id:'1101',
            type:'2',//问题类型1单选，2多选
            order:100,//问题显示顺序
            question:'做什么事都感到没有兴趣或乐趣？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1105',
            type:'2',//问题类型1单选，2多选
            order:105,//问题显示顺序
            question:'感到心情低落？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1120',
            type:'2',//问题类型1单选，2多选
            order:120,//问题显示顺序
            question:'入睡困难，很难熟睡或睡太多？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1125',
            type:'2',//问题类型1单选，2多选
            order:125,//问题显示顺序
            question:'感到疲劳或无精打采？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1130',
            type:'2',//问题类型1单选，2多选
            order:130,//问题显示顺序
            question:'胃口不好或者吃太多？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1135',
            type:'2',//问题类型1单选，2多选
            order:135,//问题显示顺序
            question:'觉得自己很糟，或很失败，或让自己或家里人失望？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1140',
            type:'2',//问题类型1单选，2多选
            order:140,//问题显示顺序
            question:'注意力很难集中，例如阅读报纸或看电视？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1145',
            type:'2',//问题类型1单选，2多选
            order:145,//问题显示顺序
            question:'动作或说话速度缓慢到别人可察觉的程度，或正好相反——您烦躁或坐立不安，动来动去的情况比平常更严重？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
        {
            id:'1150',
            type:'2',//问题类型1单选，2多选
            order:150,//问题显示顺序
            question:'有不如死掉或用某种方式伤害自己的念头？',
            options:[
                {
                    'name':'完全不会',
                    'score':0,
                },
                {
                    'name':'几天',
                    'score':1
                },
                {
                    'name':'一半以上的日子',
                    'score':2
                },
                {
                    'name':'几乎每天',
                    'score':3
                },
            ]
        },
    ],
    sleepQuestion:[//阿森斯失眠量表（AIS）
        {
            id:'1201',
            type:'3',//问题类型1单选，2多选
            order:201,//问题显示顺序
            question:'入睡时间（关灯后到睡着时间）？',
            options:[
                {
                    'name':'没问题',
                    'score':0,
                },
                {
                    'name':'轻微延迟',
                    'score':1
                },
                {
                    'name':'显著延迟',
                    'score':2
                },
                {
                    'name':'严重延迟或没有睡觉',
                    'score':3
                },
            ]
        },
        {
            id:'1205',
            type:'3',//问题类型1单选，2多选
            order:205,//问题显示顺序
            question:'夜间苏醒？',
            options:[
                {
                    'name':'没问题',
                    'score':0,
                },
                {
                    'name':'轻微影响',
                    'score':1
                },
                {
                    'name':'显著影响',
                    'score':2
                },
                {
                    'name':'严重影响或没有睡觉',
                    'score':3
                },
            ]
        },
        {
            id:'1210',
            type:'3',//问题类型1单选，2多选
            order:210,//问题显示顺序
            question:'比期望的时间早醒？',
            options:[
                {
                    'name':'没问题',
                    'score':0,
                },
                {
                    'name':'轻微早醒',
                    'score':1
                },
                {
                    'name':'显著早醒',
                    'score':2
                },
                {
                    'name':'严重提早或没有睡觉',
                    'score':3
                },
            ]
        },
        {
            id:'1215',
            type:'3',//问题类型1单选，2多选
            order:215,//问题显示顺序
            question:'总睡眠时间？',
            options:[
                {
                    'name':'足够',
                    'score':0,
                },
                {
                    'name':'轻微不足',
                    'score':1
                },
                {
                    'name':'显著不足',
                    'score':2
                },
                {
                    'name':'严重不足或没有睡觉',
                    'score':3
                },
            ]
        },
        {
            id:'1220',
            type:'3',//问题类型1单选，2多选
            order:220,//问题显示顺序
            question:'总睡觉质量（无论睡多长）？',
            options:[
                {
                    'name':'满意',
                    'score':0,
                },
                {
                    'name':'轻微不满',
                    'score':1
                },
                {
                    'name':'显著不满',
                    'score':2
                },
                {
                    'name':'严重不满或没有睡觉',
                    'score':3
                },
            ]
        },
        {
            id:'1230',
            type:'3',//问题类型1单选，2多选
            order:230,//问题显示顺序
            question:'白天情绪？',
            options:[
                {
                    'name':'正常',
                    'score':0,
                },
                {
                    'name':'轻微低落',
                    'score':1
                },
                {
                    'name':'显著低落',
                    'score':2
                },
                {
                    'name':'严重低落',
                    'score':3
                },
            ]
        },
        {
            id:'1235',
            type:'3',//问题类型1单选，2多选
            order:235,//问题显示顺序
            question:'白天身体功能（体力和精神，如记忆力、认识和注意力等）？',
            options:[
                {
                    'name':'足够',
                    'score':0,
                },
                {
                    'name':'轻微影响',
                    'score':1
                },
                {
                    'name':'显著影响',
                    'score':2
                },
                {
                    'name':'严重影响',
                    'score':3
                },
            ]
        },
        {
            id:'1240',
            type:'3',//问题类型1单选，2多选
            order:240,//问题显示顺序
            question:'白天思睡？',
            options:[
                {
                    'name':'无思睡',
                    'score':0,
                },
                {
                    'name':'轻微思睡',
                    'score':1
                },
                {
                    'name':'显著思睡',
                    'score':2
                },
                {
                    'name':'严重思睡',
                    'score':3
                },
            ]
        }
    ],
    userId:"",
    userName:"",
    hospitalCode:"邵逸夫医院"
  },
  actions,
  mutations,
})
export default store